// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hroubzuslzazndgebwam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhyb3VienVzbHphem5kZ2Vid2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1ODU2NjQsImV4cCI6MjA3ODE2MTY2NH0.KQl4MiYUmw4kg_1qS-TpNC92xNdHtj1lA7AJvQqVYYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);